Stepper Feature
EnsembleUI/ensemble-react pull request #462
Opened 2024-03-11 17:17 UTC by sibteali786

## Describe your changes
- Trying to fix activeStepIndex to support expressions 
### Screenshots [Optional]

## Issue ticket number and link

Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

2024-03-11 17:19 UTC, sibteali786 commented
@evshi need some help here, first when I update step using Next it does not work, and remains on old value ? Second is it a right approach what i am doing here to make a separate hook for this ?

2024-03-11 17:22 UTC, sibteali786 commented
The example is at `/widgets` screen at bottom

2024-03-11 17:41 UTC, evshi reviewed
I think what you're looking for is just a `useEffect` hook that syncs the evaluated attribute to the component local state

2024-03-12 17:39 UTC, evshi commented on packages/runtime/src/widgets/Stepper/Stepper.tsx
> +  });
Remove this. Just move the useEffect hook after useRegisterBindings.

2024-03-12 17:39 UTC, evshi commented on packages/runtime/src/widgets/Stepper/Stepper.tsx
> -  activeStepIndex?: number;
This can still be null?

2024-03-12 19:49 UTC, evshi commented on packages/runtime/src/widgets/Stepper/Stepper.tsx
> +    if (isString(activeStep) && isExpression(activeStep)) {
You can check the props value so you don't need to overload your state variable. Your state variable should always just be an integer

2024-03-13 16:35 UTC, evshi approved these changes

2024-03-13 16:35 UTC, evshi requested changes

2024-03-13 16:35 UTC, evshi commented on packages/runtime/src/widgets/Stepper/Stepper.tsx
> +import { isString } from "antd/es/button";
wrong import use from lodash-es

2024-03-14 08:18 UTC, sibteali786 commented
there is one more issue happening here @evshi i forgot to discuss it yesterday, the state of stepper is not being updated when we change a step, it does change step but not the value of activeStepIndex nor stiveStep . This way it always stays what it was initialized with ?

2024-03-14 16:50 UTC, merged