added curPage in datagrid
EnsembleUI/ensemble-react pull request #564
Opened 2024-05-06 16:49 UTC by sagardspeed2

## Describe your changes
added curPage in dataGrid

### Screenshots [Optional]

## Issue ticket number and link

Closes #559 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

2024-05-06 18:00 UTC, evshi requested changes
I'm not sure when you added `skipFirstRender` but why is that there?

2024-05-06 18:09 UTC, sagardspeed2 commented
> I'm not sure when you added `skipFirstRender` but why is that there?

`skipFirstRender` is needed to just void unnecessary API call on the dataGrid widget register, API should only render on the page change or pageSize change

2024-05-07 15:30 UTC, evshi commented
Can you please remove? You don't need it.

2024-05-07 19:41 UTC, evshi commented on packages/runtime/src/widgets/DataGrid/DataGrid.tsx
> +      setPage,
This is an API breaking change by renaming the function. You need to keep the key the same.

2024-05-07 19:41 UTC, evshi commented on packages/runtime/src/widgets/DataGrid/DataGrid.tsx
> +  const setPage = (page: number) => {
Use `useCallback`

2024-05-07 19:59 UTC, evshi commented on packages/runtime/src/widgets/DataGrid/DataGrid.tsx
> +    (n: number) => {
nit: rename to better variables.

2024-05-07 19:59 UTC, evshi approved these changes

2024-05-08 05:50 UTC, merged