fix: added inputNumber for input type number
EnsembleUI/ensemble-react pull request #790
Opened 2024-08-16 10:59 UTC by sagardspeed2

## Describe your changes
Added inputNumber for input type number

### Screenshots [Optional]

## Issue ticket number and link

Closes #782 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

2024-08-19 16:18 UTC, evshi requested changes
@sagardspeed2 this doesn't meet the requirements at all. I am able to type way more digits than should be allowed. `InputNumber` also has completely different styling.

2024-08-20 16:41 UTC, evshi commented on packages/runtime/src/widgets/Form/TextInput.tsx
> +      if (values?.inputType !== "number") {
Let's only attach the handler if the inputType is number.

2024-08-20 16:41 UTC, evshi commented on packages/runtime/src/widgets/Form/TextInput.tsx
> +        ["c", "v", "x"].includes(e.key.toLowerCase());
I think just check if the meta/ctrl key is pressed and let the default behavior go through if so.

2024-08-20 17:08 UTC, evshi commented on packages/runtime/src/widgets/Form/TextInput.tsx
> +      const isCopyPasteCut = e.ctrlKey || e.metaKey;
This may be a better solution than checking for keys individually https://stackoverflow.com/a/70401792

2024-08-20 17:09 UTC, evshi commented
Also can you please add some tests for this?

2024-08-21 16:40 UTC, evshi commented
@sagardspeed2 can you please add some unit tests for this

2024-08-21 16:41 UTC, sagardspeed2 commented
> @sagardspeed2 can you please add some unit tests for this

I am writing a unit tests for this

2024-08-23 15:43 UTC, evshi approved these changes

2024-08-23 15:43 UTC, evshi commented on packages/runtime/src/widgets/Form/__tests__/TextInput.test.tsx
> +global.ResizeObserver = require("resize-observer-polyfill");
This isn't needed anymore I did it once in setuptests.js

2024-08-25 18:25 UTC, merged