fix: added support for custom fonts in ensemble studio
EnsembleUI/ensemble-react pull request #803
Opened 2024-08-28 12:53 UTC by sagardspeed2

## Describe your changes
Added support for custom fonts in ensemble studio

### Screenshots [Optional]

## Issue ticket number and link

Closes #762 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

2024-08-28 16:50 UTC, evshi commented on packages/framework/src/loader.ts
> +      const font = document as { [key: string]: unknown };
FontDTO type should reflect what the firebase document is like and should be what you cast to here.

2024-08-28 16:50 UTC, evshi commented on packages/framework/src/hooks/useFonts.ts
> +      return new FontFace(font.family, `url(${font.url})`, {});
What about the font options?

2024-08-28 17:28 UTC, sagardspeed2 commented
@evshi this PR is still not ready for review, I am still working on it

2024-08-28 20:20 UTC, amin-nas commented
@sagardspeed2 @evshi please see latest EDL example here:
https://github.com/EnsembleUI/ensemble/issues/1576

2024-09-23 23:29 UTC, evshi requested changes

2024-09-23 23:29 UTC, evshi commented on packages/framework/tsconfig.json
> +  }
this should go in the base config.

2024-09-23 23:29 UTC, evshi commented on packages/framework/src/shared/dto.ts
> +export interface FontDTO {
Just keep `EnsembleFontModel` and remove this, rename the FirebaseFontDTO to FontDTO. Convert things later so models reference models and dtos reference dtos, etc.

DTO = Data Transfer Object, it represents the data over the wire.

2024-09-23 23:29 UTC, evshi commented on packages/framework/src/hooks/useFonts.ts
> +    };
You can just use `forEach` and you don't need a new function declaration ehre.

2024-09-23 23:29 UTC, evshi commented on packages/framework/src/hooks/useApplicationContext.tsx
> +  useFonts(app.fonts || []);
Handle nullability in the hook itself.

2024-09-24 17:18 UTC, evshi approved these changes

2024-09-24 17:18 UTC, evshi commented on packages/framework/src/hooks/useFonts.ts
> +  const loadFontFace = (font: EnsembleFontModel): unknown => {
nit: just inline this or put it inside the hook body so it's not redeclared.

2024-09-27 16:29 UTC, evshi commented
@sagardspeed2 is this ready to be merged?

2024-09-27 16:31 UTC, sagardspeed2 commented
> @sagardspeed2 is this ready to be merged?

@evshi we need to run this in production first to clear the cors issue
`gsutil cors set cors.json <bucket_name>`

and I don't have the production firebase access

2024-09-27 16:37 UTC, evshi commented
@sagardspeed2 why do we need to run that command? @justEhmadSaeed is this something you can help with?

2024-09-27 16:44 UTC, sagardspeed2 commented
@evshi we are trying to fetch the font files from the firebase and there is cors added for the origin. so when I tested it was giving cors error while fetching the font files from the firebase. so I used this command for dev firebase storage, and it works.

2024-09-27 18:55 UTC, justEhmadSaeed commented
@sagardspeed2 i don't understand why you need to set cors for fonts when it's already being fetched by the prod app. if you want to fetch the prod data on the local, then it's disabled intentionally.

2024-09-30 05:22 UTC, merged